name: Docker Build Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  DOCKER_USERNAME: '${{secrets.DOCKER_USERNAME}}'
  DOCKER_PASSWORD: '${{secrets.DOCKER_PASSWORD}}'
  DOCKER_REPO: '${{secrets.DOCKER_REPO}}'
  KUBERNETES_SECRET: '${{secrets.KUBERNETES_SECRET}}'
  KUBERNETES_URL: '${{secrets.KUBERNETES_URL}}'

jobs:
  create-user-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build user service docker image
        run: docker build . --file Dockerfile -t "$DOCKER_USERNAME/$DOCKER_REPO:latest"
      - name: Push user service docker image
        run: docker push "$DOCKER_USERNAME/$DOCKER_REPO:latest"

  deployment:
    needs: [create-user-image]
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{secrets.KUBERNETES_URL}}
          k8s-secret: ${{secrets.KUBERNETES_SECRET}}
      - uses: actions/checkout@v2
      - uses: azure/k8s-deploy@v4
        with:
          namespace: default
          manifests: |
             manifests
